name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    description: 'compiler to use'
  build_type:
    required: true
    description: 'build type to use'
  generator:
    required: true
    description: 'generator to use'

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
            ${{ env.HOME }}/.ccache
            ${{ env.HOME }}/.xmake-cache
            ${{ env.HOME }}/.xmake
            ${{ env.HOME }}/.cache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}}}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
