name: ci
on:
  pull_request:
    branches:
      - main
      - dev

env:
  CLANG_TIDY_VERSION: "16.0.0"
  VERBOSE: 1

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compiler:
          - llvm
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v3

      - name: Install scoop
        if: ${{ matrix.os == 'windows-latest' }}
        uses: MinoruSekine/setup-scoop@v2

      - name: Install xmake
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          scoop install xmake

      - name: Install xmake
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt update
          sudo apt install xmake

      - name: Install xmake
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install xmake
          xmake --version

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        if: ${{ matrix.os != 'macos-latest' }}
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          make: true
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}
          cppcheck: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          make: true
          ccache: true
          clangtidy: 15.0.0
          cppcheck: true

      - name: Configure Xmake
        run: |
          xmake f -m ${{matrix.build_type}} --verbose -y

      - name: Build Xmake
        run: |
          xmake -v -j 4

      - name: Unix - Test and coverage
        working-directory: ./build
        run: |
          xmake run test
