name: ci_windows
on:
  pull_request:
    branches:
      - main
      - dev

env:
  CLANG_TIDY_VERSION: "16.0.0"
  VERBOSE: 1

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
        compiler:
          - llvm
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'

      - name: Setup Git for Windows' minimal SDK
        uses: git-for-windows/setup-git-for-windows-sdk@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Configure Xmake
        run: |
          xmake update -s dev
          xmake f -m ${{matrix.build_type}} --verbose -y --toolchain=clang

      - name: Build Xmake
        run: |
          xmake -v -j 4

      - name: Unix - Test and coverage
        working-directory: ./build
        run: |
          xmake run test
