name: ci_windows
on:
  pull_request:
    branches:
      - main
      - dev

env:
  CLANG_TIDY_VERSION: "16.0.0"
  VERBOSE: 1

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
        compiler:
          - llvm
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        if: ${{ matrix.os != 'macos-latest' }}
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          make: true
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}
          cppcheck: true

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Configure Xmake
        run: |
          xmake f -m ${{matrix.build_type}} --verbose -y --toolchain=clang --sdk=C:\Users\runneradmin\llvm\bin

      - name: Build Xmake
        run: |
          xmake -v -j 4

      - name: Unix - Test and coverage
        working-directory: ./build
        run: |
          xmake run test
